spring.application.name=Chung_Khoan
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=QUANLYGIAODICHCHUNGKHOAN;encrypt=false;trustServerCertificate=true;charset=UTF-8

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Hibernate configurations
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# Các khung giờ phiên giao dịch

# Giờ mở phiên ATO
trading-time.ato-start=08:45
# Giờ kết thúc phiên ATO
trading-time.ato-end=09:00
# Giờ kết thúc phiên LO
trading-time.lo-end=21:00
# Giờ kết thúc phiên ATC
trading-time.atc-end=21:30

# Thời điểm xử lý khớp lệnh LO/ATO/ATC (Xử lý khớp/hủy lệnh ngay đúng thời điểm này)
trading-time.cron-ato-check=0 46 08 * * MON-SUN
trading-time.cron-atc-check=0 34 21 * * MON-SUN
